annotations:
    # screwdriver.cd/chainPR: true
    screwdriver.cd/restrictPR: all
jobs: 
    main:
        requires: [~commit, ~pr]
        image: node:12
        steps:
            - sayitout: echo sayitout
            - check: echo pass
            - echo: echo
            - status: |
                meta set meta.status.coverage '{"status":"PENDING","message":"Coverage is below 80%."}'
                meta set meta.status.findbugs '{"status":"PENDING","message":"Some code Refactoring is needed"}'
                meta set meta.status.findbugs '{"status":"SUCCESS","message":"No Bugs Found!"}'
                meta set meta.status.lint '{"status":"FAILED","message":"Resolve Lint errors"}'
    build-node12:
        image: node:12
        steps: 
            - init: npm install
            - test: npm test
            - publish: |
                echo "publishing against node 8"
                meta set publish.node12 `date +%s`
                sleep 1
        requires: [main]
        
    # B and C will run in parallel
    build-node10:
        image: node:10
        steps:
            - init: npm install
            - test: npm test
            - publish: |
                echo "publishing against node 10"
                meta set publish.node10 `date +%s`
                sleep 3
        requires: [main]
    delploy-stage:  
        image: node:10
        steps:
            - verify: echo verify
            - deploy-8: echo "deploying node12 $(meta get publish.node12)"
            - deploy-10: echo "deploying node10 $(meta get publish.node10)"
        requires: [build-node10, build-node12, sd@12:main-2]
    delploy-prod:  
        image: node:10
        steps:
            - verify: echo verify
            - deploy-8: echo "deploying node12 $(meta get publish.node12)"
            - deploy-10: echo "deploying node10 $(meta get publish.node10)"
        requires: [delploy-stage]
    rollback-prod:
        image: node:10
        requires: [~sd@12:main]
        steps:
            - rollback-8: |
                echo "rolling back to version $(meta get publish.node12)"
            - rollback-10: |
                echo "rolling back to version $(meta get publish.node10)"